// types — message and tool types for OpenAI-compatible /chat/completions (SPEC §6.2).
//
// We prioritize a practical serialization shape over strict schemas. Heavy use of
// `serde(skip_serializing_if = ...)` keeps the request payload small.
//
// Message is an internally-tagged enum so each role's required fields are enforced at compile time.
//   - Tool variant: content / name / tool_call_id are all required (enforced by the type)
//   - Assistant variant: content is optional; tool_calls is optional
//   - User / System variants: content is required

use serde::{Deserialize, Serialize};

/// One `/chat/completions` message. The `role` discriminator chooses the variant.
///
/// `#[serde(tag = "role", rename_all = "lowercase")]` produces OpenAI-compatible
/// flat JSON like `{"role": "user", "content": "..."}`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "role", rename_all = "lowercase")]
pub enum Message {
    System {
        content: String,
    },
    User {
        content: String,
    },
    /// LLM response. Either or both of `content` / `tool_calls` may be present.
    Assistant {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        content: Option<String>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        tool_calls: Vec<ToolCall>,
    },
    /// Tool execution result. All three fields required (SPEC §6.2).
    Tool {
        content: String,
        /// Must match the originating assistant.tool_calls[i].id.
        tool_call_id: String,
        /// The MCP public name (`<server>__<tool>` form). Optional in the OpenAI
        /// spec, but we always set it.
        name: String,
    },
}

impl Message {
    pub fn system(content: impl Into<String>) -> Self {
        Message::System { content: content.into() }
    }
    pub fn user(content: impl Into<String>) -> Self {
        Message::User { content: content.into() }
    }
    pub fn assistant_text(content: impl Into<String>) -> Self {
        Message::Assistant { content: Some(content.into()), tool_calls: Vec::new() }
    }
    pub fn tool(
        tool_call_id: impl Into<String>,
        name: impl Into<String>,
        content: impl Into<String>,
    ) -> Self {
        Message::Tool {
            tool_call_id: tool_call_id.into(),
            name: name.into(),
            content: content.into(),
        }
    }

    /// Return the `Assistant` variant's tool_calls; empty slice for other variants.
    ///
    /// Used by the agent loop to decide "are there tool_calls to run".
    pub fn tool_calls(&self) -> &[ToolCall] {
        match self {
            Message::Assistant { tool_calls, .. } => tool_calls,
            _ => &[],
        }
    }
}

/// One tool invocation requested by the assistant.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    pub id: String,
    /// Currently always `"function"` for OpenAI-compatible APIs.
    #[serde(rename = "type")]
    pub kind: String,
    pub function: FunctionCall,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCall {
    pub name: String,
    /// JSON string. SSE fragments it across chunks, so we concatenate (SPEC §6.1).
    pub arguments: String,
}

/// Tool definition exposed to the LLM (MCP-sourced; generated by `as_openai_tools()` in M6).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tool {
    /// Currently always `"function"`.
    #[serde(rename = "type")]
    pub kind: String,
    pub function: ToolFunction,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolFunction {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// JSON Schema. The MCP-side schema is fed through verbatim.
    pub parameters: serde_json::Value,
}

/// `/chat/completions` request body. `stream: true` is fixed (SPEC §1, §6).
#[derive(Debug, Clone, Serialize)]
pub struct ChatRequest {
    pub model: String,
    pub messages: Vec<Message>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<Tool>>,
    pub stream: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_message_serializes_minimal_fields() {
        let m = Message::user("hi");
        let v = serde_json::to_value(&m).unwrap();
        assert_eq!(v["role"], "user");
        assert_eq!(v["content"], "hi");
        // No tool_calls / tool_call_id / name on user messages.
        assert!(v.get("tool_calls").is_none());
        assert!(v.get("tool_call_id").is_none());
        assert!(v.get("name").is_none());
    }

    #[test]
    fn assistant_with_tool_calls_serializes_array() {
        let m = Message::Assistant {
            content: None,
            tool_calls: vec![ToolCall {
                id: "call_1".into(),
                kind: "function".into(),
                function: FunctionCall {
                    name: "do_it".into(),
                    arguments: r#"{"x":1}"#.into(),
                },
            }],
        };
        let v = serde_json::to_value(&m).unwrap();
        assert_eq!(v["role"], "assistant");
        assert!(v.get("content").is_none());
        assert_eq!(v["tool_calls"][0]["id"], "call_1");
        assert_eq!(v["tool_calls"][0]["type"], "function");
        assert_eq!(v["tool_calls"][0]["function"]["name"], "do_it");
    }

    #[test]
    fn assistant_text_only_omits_tool_calls() {
        let m = Message::assistant_text("hello");
        let v = serde_json::to_value(&m).unwrap();
        assert_eq!(v["role"], "assistant");
        assert_eq!(v["content"], "hello");
        // tool_calls is empty so the field itself disappears.
        assert!(v.get("tool_calls").is_none());
    }

    #[test]
    fn chat_request_omits_tools_when_none() {
        let req = ChatRequest {
            model: "gpt-4o-mini".into(),
            messages: vec![Message::user("ping")],
            tools: None,
            stream: true,
        };
        let v = serde_json::to_value(&req).unwrap();
        assert_eq!(v["stream"], true);
        assert!(v.get("tools").is_none());
    }

    #[test]
    fn tool_message_has_required_fields() {
        let m = Message::tool("call_42", "my_tool", "result text");
        assert!(matches!(m, Message::Tool { .. }));
        if let Message::Tool { tool_call_id, name, content } = &m {
            assert_eq!(tool_call_id, "call_42");
            assert_eq!(name, "my_tool");
            assert_eq!(content, "result text");
        }
    }

    #[test]
    fn tool_message_serializes_correctly() {
        let m = Message::tool("cid", "fn_name", "ok");
        let v = serde_json::to_value(&m).unwrap();
        assert_eq!(v["role"], "tool");
        assert_eq!(v["tool_call_id"], "cid");
        assert_eq!(v["name"], "fn_name");
        assert_eq!(v["content"], "ok");
        // tool_calls doesn't exist on the tool variant.
        assert!(v.get("tool_calls").is_none());
    }

    #[test]
    fn tool_message_missing_tool_call_id_fails_to_deserialize() {
        // tool_call_id is required — deserialization should fail without it.
        let json = r#"{"role":"tool","name":"fn","content":"ok"}"#;
        let r: Result<Message, _> = serde_json::from_str(json);
        assert!(r.is_err(), "tool_call_id should be required for the tool variant");
    }

    #[test]
    fn tool_calls_helper_returns_assistant_tool_calls() {
        let m = Message::Assistant {
            content: None,
            tool_calls: vec![ToolCall {
                id: "x".into(),
                kind: "function".into(),
                function: FunctionCall { name: "f".into(), arguments: "{}".into() },
            }],
        };
        assert_eq!(m.tool_calls().len(), 1);
        // Other variants return an empty slice.
        assert!(Message::user("hi").tool_calls().is_empty());
        assert!(Message::tool("id", "n", "c").tool_calls().is_empty());
    }
}
